version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app  # Монтируем проект в контейнер
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_SETTINGS_MODULE=config.settings

  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    volumes:
      - .:/app  # Монтируем проект в контейнер
    environment:
      - BOT_API_TOKEN=${BOT_API_TOKEN}
      - DJANGO_SETTINGS_MODULE=config.settings
    depends_on:
      - web
