version: '3.8'

services:
  # Сервис для Django
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_SETTINGS_MODULE=config.settings

  # Сервис для бота
  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile  # Указываем Dockerfile для бота
    volumes:
      - .:/app  # Монтируем всю директорию проекта
    environment:
      - BOT_API_TOKEN=${BOT_API_TOKEN}
      - DJANGO_SETTINGS_MODULE=config.settings
